version: '3.9'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - my-network

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "80:80"
    depends_on:
      - minio

    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - BUCKET_NAME=my-bucket
    volumes:
      - minio-data:/app/minio-data
    networks:
      - my-network

volumes:
  minio-data:

networks:
  my-network:
